# translations for the whole website
jms_translation: # useage: php bin/console translation:extract de --config=app --output-format=xliff --keep
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs, public, tests]
            output-format: xliff
#            extractors: [alias_of_the_extractor]