knp_snappy:
    temporary_folder: "%env(temporary_folder)"
    process_timeout: 20 # In seconds
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            no-outline: true
            page-size: A4
            # Recommended to set UTF-8 as default encoding :)
            encoding: UTF-8
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
