# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
        transport: '%mailer_transport%'
        host: '%env(mailer_host)%'
        username: '%env(mailer_user)%'
        password: '%env(mailer_password)%'
        port: 587
        encryption: tls
        auth_mode: login
        spool: { type: memory }
